---
- name: Verify
  hosts: all
  vars_files:
    - ../../defaults/main.yml
  tasks:
    - name: Gather the package manager facts
      ansible.builtin.package_facts:
        manager: auto
    - name: Assert that following packages are installed
      ansible.builtin.assert:
        that: "item in ansible_facts.packages"
      with_items: "{{ installed_packages }}"
